name: Build website
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@master
        with:
          args: --output _site
          install_dependencies: true
      - name: Deploy to GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          publish_dir: _site 
          publish_branch: gh-pages
          github_token: ${{ secrets.ACCESS_TOKEN }}
          cname: meddea.global
